### ISSUE TITLE
👋

### ISSUE THREAD

**Issue by zeke** [package-community/package-community.github.io#1]
Hi! This sounds like an interest project. I will be watching and looking forward to seeing what kinds of conversations happen here.

Package management is a topic of great importance to me. I've been working on [nice registry](https://github.com/nice-registry/about#readme), a collection of tools that make it easier to work with the npm package registry and learn things from it. You've inspired me to update its readme tonight: https://github.com/nice-registry/about#readme

**Comment by zkat** [comment]
Cool! We also have https://github.com/package-community/discussions for more chatty stuff, though it's pretty quiet right now. Most conversations have been happening over in the Discord right now. 👋

**Comment by Daniel15** [comment]
Where is the Discord, @zkat!

**Comment by zkat** [comment]
@Daniel15 It's linked from https://package.community/: https://discord.gg/RkxC4cA

**Comment by zeke** [comment]
Closing this out, as it's not an actionable issue so much as a greeting. :)

**Comment by Daniel15** [comment]
@zkat The link doesn't work for me 😢 
![](http://ss.dan.cx/2017/07/chrome_06-16.21.01.png)

**Comment by zkat** [comment]
@Daniel15 I've set the link to never expire. Does it work now? (sorry, new to Discord hosting)

**Comment by Daniel15** [comment]
It works now! Thanks @zkat! 😃
